default_agent: iot_sensor_analysis_agent
agents:
  iot_sensor_analysis_agent:
    name: iot_sensor_analysis_agent
    entrypoint: /Users/rishabhtiwari/aws_iot_project/agentcore/strands_agent_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::381492092651:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-07898fecc7
      execution_role_auto_create: false
      account: '381492092651'
      region: us-east-1
      ecr_repository: 381492092651.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-iot_sensor_analysis_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: iot_sensor_analysis_agent-Zz1vVbFKy9
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:381492092651:runtime/iot_sensor_analysis_agent-Zz1vVbFKy9
      agent_session_id: 3fe143ef-85c7-4773-a595-06a7ade0e21e
    codebuild:
      project_name: bedrock-agentcore-iot_sensor_analysis_agent-builder
      execution_role: arn:aws:iam::381492092651:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-07898fecc7
      source_bucket: bedrock-agentcore-codebuild-sources-381492092651-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
